interface handler {
    use jabratech:common/types.{response};
    use types.{interpolator-data, interpolator-config, update-interpolator-config,update-interpolator-data, update-weekend-weight-request, update-adjustment-request};

    get-data: func(currency: s8, date: option<string>) -> result<list<interpolator-data>, response>;
    get-config: func(currency: s8) -> result<interpolator-config, response>;
    update-config: func(request: update-interpolator-config) -> result<bool, response>;
    update-data: func(request: update-interpolator-data) -> result<bool, response>;
    update-weekend-weights: func(request: update-weekend-weight-request) -> result<bool, response>;
    update-adjustment: func(request: update-adjustment-request) -> result<bool, response>;
}
