interface types {

    record interpolator-data {
        date: string,
        day-of-week: string,
        weight: f64,
        is-add: bool,
        is-multiply: bool,
        md: string,
        cd: string,
        adjustment: f64
    }

    record interpolator-config {
        initial-value: f64,
        mean-rev: f64,
        decay: f64,
        saturday-weight: f64,
        multiply-saturday: bool,
        add-saturday: bool,
        sunday-weight: f64,
        multiply-sunday: bool,
        add-sunday: bool
    }

    record update-interpolator-config {
        user-email: string,
        initial-value: f64,
        mean-rev: f64,
        decay: f64,
        currency: s8,
        saturday-weight: option<f64>,
        multiply-saturday: bool,
        add-saturday: bool,
        sunday-weight: option<f64>,
        multiply-sunday: bool,
        add-sunday: bool
    }

    record update-interpolator-data {
        user-email: string,
        currency: s8,
        date: string,
        weight: f64,
        is-add: bool,
        is-multiply: bool,
        adjustment: option<f64>
    }

    record update-weekend-weight-request {
        user-email: string,
        currency: s8,
        saturday-weight: option<f64>,
        multiply-saturday: bool,
        add-saturday: bool,
        sunday-weight: option<f64>,
        multiply-sunday: bool,
        add-sunday: bool
    }
}
